version: '3.8'

services:
  nextapp:
    build: .
    container_name: next_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # 从主机映射到容器
      - /www/ClipNote/sitemap.xml:/app/public/sitemap.xml
      - /www/ClipNote/sitemap-knowledge.xml:/app/public/sitemap-knowledge.xml
      # 添加应用程序代码映射
      - ./:/app
      # 防止覆盖 node_modules 和 .next
      - /app/node_modules
      - /app/.next
    working_dir: /app
    command: npm run start
