version: '3.8'

services:
  nextapp:
    build: .
    container_name: next_app
    volumes:
      - /www/ClipNote/sitemap.xml:/app/public/sitemap.xml
      - /www/ClipNote/sitemap-knowledge.xml:/app/public/sitemap-knowledge.xml
      - /www/ClipNote/sitemap-exercises.xml:/app/public/sitemap-exercises.xml
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # 按需添加volume