version: '3.8'

services:
  nextapp:
    build: .
    container_name: next_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # 映射 sitemap 文件到物理机指定路径
      - ./public/sitemap.xml:/www/ClipNote/sitemap.xml
      - ./public/sitemap-0.xml:/www/ClipNote/sitemap-0.xml
    # 按需添加volume
