version: '3.8'

services:
  nextapp:
    build: .
    container_name: next_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # 从主机映射到容器（注意方向反转了）
      - /www/ClipNote/sitemap.xml:/app/public/sitemap.xml
      - /www/ClipNote/sitemap-0.xml:/app/public/sitemap-0.xml
    # 按需添加volume
